<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Brand;
use App\Models\Product;
use App\Models\HeroSlide;
use Illuminate\Database\Seeder;

/**
 * Real catalog data exported from the local working database —
 * generated, not hand-written. Re-run the export if the local
 * catalog changes before the next deploy.
 */
class ProductionDataSeeder extends Seeder
{
    public function run(): void
    {
        $categories = array (
  0 => 
  array (
    'name' => 'الملابس النسائية',
    'name_he' => 'בגדי נשים',
    'name_en' => 'Women\'s Clothing',
    'icon' => '👗',
    'image' => 'categories/cat-1.png',
    'key' => 'women-clothing',
    'sort_order' => 1,
    'is_active' => true,
  ),
  1 => 
  array (
    'name' => 'شنط نسائية',
    'name_he' => 'תיקי נשים',
    'name_en' => 'Women\'s Bags',
    'icon' => '👜',
    'image' => 'categories/cat-2.png',
    'key' => 'women-bags',
    'sort_order' => 2,
    'is_active' => true,
  ),
  2 => 
  array (
    'name' => 'الأحذية النسائية',
    'name_he' => 'נעלי נשים',
    'name_en' => 'Women\'s Shoes',
    'icon' => '👠',
    'image' => 'categories/cat-3.png',
    'key' => 'women-shoes',
    'sort_order' => 3,
    'is_active' => true,
  ),
  3 => 
  array (
    'name' => 'الملابس الرجالية',
    'name_he' => 'בגדי גברים',
    'name_en' => 'Men\'s Clothing',
    'icon' => '👔',
    'image' => 'categories/cat-4.png',
    'key' => 'men-clothing',
    'sort_order' => 4,
    'is_active' => true,
  ),
  4 => 
  array (
    'name' => 'الأحذية الرجالية',
    'name_he' => 'נעלי גברים',
    'name_en' => 'Men\'s Shoes',
    'icon' => '👞',
    'image' => 'categories/cat-5.png',
    'key' => 'men-shoes',
    'sort_order' => 5,
    'is_active' => true,
  ),
  5 => 
  array (
    'name' => 'أطفال',
    'name_he' => 'ילדים',
    'name_en' => 'Kids',
    'icon' => '🧒',
    'image' => 'categories/cat-6.png',
    'key' => 'kids',
    'sort_order' => 6,
    'is_active' => true,
  ),
);
        $categoryIds = [];
        foreach ($categories as $cat) {
            $categoryIds[$cat['key']] = Category::updateOrCreate(['key' => $cat['key']], $cat)->id;
        }

        $brands = array (
  0 => 
  array (
    'name' => 'Nike',
    'logo' => NULL,
    'sort_order' => 1,
    'is_active' => true,
  ),
  1 => 
  array (
    'name' => 'Adidas',
    'logo' => NULL,
    'sort_order' => 2,
    'is_active' => true,
  ),
  2 => 
  array (
    'name' => 'Zara',
    'logo' => NULL,
    'sort_order' => 3,
    'is_active' => true,
  ),
  3 => 
  array (
    'name' => 'U.S Polo',
    'logo' => NULL,
    'sort_order' => 4,
    'is_active' => true,
  ),
  4 => 
  array (
    'name' => 'The North Face',
    'logo' => NULL,
    'sort_order' => 5,
    'is_active' => true,
  ),
  5 => 
  array (
    'name' => 'Timberland',
    'logo' => NULL,
    'sort_order' => 6,
    'is_active' => true,
  ),
  6 => 
  array (
    'name' => 'Balenciaga',
    'logo' => NULL,
    'sort_order' => 7,
    'is_active' => true,
  ),
  7 => 
  array (
    'name' => 'Dr Martens',
    'logo' => NULL,
    'sort_order' => 8,
    'is_active' => true,
  ),
);
        $brandIds = [];
        foreach ($brands as $brand) {
            $brandIds[$brand['name']] = Brand::updateOrCreate(['name' => $brand['name']], $brand)->id;
        }

        $products = array (
  0 => 
  array (
    'name' => 'تيشيرت رياضي نسائي',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'تيشيرت نسائي رياضي مريح بلونين متوفرين',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-1.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'خصم',
    'price' => 180.0,
    'wholesale_price' => NULL,
    'compare_price' => 250.0,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 1,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'S',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'M',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => 'L',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => 'S',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
      4 => 
      array (
        'size' => 'M',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 4,
      ),
      5 => 
      array (
        'size' => 'L',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 5,
      ),
    ),
    'category_key' => 'women-clothing',
    'brand_name' => 'Adidas',
  ),
  1 => 
  array (
    'name' => 'بلوزة نسائية أنيقة',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'بلوزة نسائية عصرية بقصة أنيقة',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-2.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'جديد',
    'price' => 120.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 17,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'S',
        'color' => 'أحمر',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#DC2626',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'M',
        'color' => 'أحمر',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#DC2626',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => 'L',
        'color' => 'أحمر',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#DC2626',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => 'M',
        'color' => 'أزرق',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#2563EB',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
    ),
    'category_key' => 'women-clothing',
    'brand_name' => 'Zara',
  ),
  2 => 
  array (
    'name' => 'حقيبة يد نسائية',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'حقيبة يد عصرية بجودة عالية ولمسة أنيقة',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-3.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 150.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 2,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'حجم كبير',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'حجم صغير',
        'color' => 'بني',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#78350F',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
    ),
    'category_key' => 'women-bags',
    'brand_name' => 'Zara',
  ),
  3 => 
  array (
    'name' => 'حذاء رياضي نسائي',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'حذاء نسائي رياضي مريح لكل الاستخدامات',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-4.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'جديد',
    'price' => 220.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 9,
    'variants' => 
    array (
      0 => 
      array (
        'size' => '36',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => '37',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => '38',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => '39',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
      4 => 
      array (
        'size' => '40',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 4,
      ),
    ),
    'category_key' => 'women-shoes',
    'brand_name' => 'Nike',
  ),
  4 => 
  array (
    'name' => 'حذاء نسائي كلاسيك',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'حذاء نسائي كلاسيكي بتصميم راقي',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-5.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'خصم',
    'price' => 180.0,
    'wholesale_price' => NULL,
    'compare_price' => 230.0,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 0,
    'variants' => 
    array (
      0 => 
      array (
        'size' => '37',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => '38',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => '39',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
    ),
    'category_key' => 'women-shoes',
    'brand_name' => NULL,
  ),
  5 => 
  array (
    'name' => 'قميص رجالي يو إس بولو',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'قميص رجالي كلاسيكي بجودة عالية وقصة مريحة',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-6.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 200.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 14,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'M',
        'color' => 'كحلي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1E3A5F',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'L',
        'color' => 'كحلي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1E3A5F',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => 'XL',
        'color' => 'كحلي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1E3A5F',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => 'L',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
      4 => 
      array (
        'size' => 'XL',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 4,
      ),
    ),
    'category_key' => 'men-clothing',
    'brand_name' => 'U.S Polo',
  ),
  6 => 
  array (
    'name' => 'تيشيرت رجالي',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'تيشيرت رجالي بتصميم عصري وخامة قطنية',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-7.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 90.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 18,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'M',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'L',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => 'XL',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
    ),
    'category_key' => 'men-clothing',
    'brand_name' => 'Zara',
  ),
  7 => 
  array (
    'name' => 'حذاء رياضي رجالي',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'حذاء رجالي رياضي بتصميم مريح وعملي',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-8.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'الأكثر مبيعاً',
    'price' => 250.0,
    'wholesale_price' => NULL,
    'compare_price' => 320.0,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 15,
    'variants' => 
    array (
      0 => 
      array (
        'size' => '40',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => '41',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => '42',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => '43',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
      4 => 
      array (
        'size' => '44',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 4,
      ),
    ),
    'category_key' => 'men-shoes',
    'brand_name' => 'Adidas',
  ),
  8 => 
  array (
    'name' => 'حذاء تمبرلاند أصلي',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'حذاء تمبرلاند أصلي بجودة عالية ومتانة',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-9.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'جديد',
    'price' => 380.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 19,
    'variants' => 
    array (
      0 => 
      array (
        'size' => '40',
        'color' => 'بني',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#78350F',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => '41',
        'color' => 'بني',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#78350F',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => '42',
        'color' => 'بني',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#78350F',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => '43',
        'color' => 'بني',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#78350F',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
    ),
    'category_key' => 'men-shoes',
    'brand_name' => 'Timberland',
  ),
  9 => 
  array (
    'name' => 'طقم رياضي أطفال',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'طقم رياضي مريح للأطفال بمقاسات متعددة',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-10.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 90.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 16,
    'variants' => 
    array (
      0 => 
      array (
        'size' => '4-6 سنوات',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => '7-9 سنوات',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => '10-12 سنوات',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
    ),
    'category_key' => 'kids',
    'brand_name' => 'Adidas',
  ),
  10 => 
  array (
    'name' => 'فستان سهرة أنيق',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'فستان سهرة بقصة عصرية وقماش فاخر — مناسب للمناسبات الخاصة.',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-11.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 260.0,
    'wholesale_price' => NULL,
    'compare_price' => 340.0,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 20,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'S',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 12,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'S',
        'color' => 'أحمر',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#DC2626',
        'stock' => 12,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => 'S',
        'color' => 'كحلي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1E3A5F',
        'stock' => 12,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => 'M',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 12,
        'sku' => NULL,
        'sort_order' => 3,
      ),
      4 => 
      array (
        'size' => 'M',
        'color' => 'أحمر',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#DC2626',
        'stock' => 12,
        'sku' => NULL,
        'sort_order' => 4,
      ),
      5 => 
      array (
        'size' => 'M',
        'color' => 'كحلي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1E3A5F',
        'stock' => 12,
        'sku' => NULL,
        'sort_order' => 5,
      ),
      6 => 
      array (
        'size' => 'L',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 12,
        'sku' => NULL,
        'sort_order' => 6,
      ),
      7 => 
      array (
        'size' => 'L',
        'color' => 'أحمر',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#DC2626',
        'stock' => 12,
        'sku' => NULL,
        'sort_order' => 7,
      ),
      8 => 
      array (
        'size' => 'L',
        'color' => 'كحلي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1E3A5F',
        'stock' => 12,
        'sku' => NULL,
        'sort_order' => 8,
      ),
    ),
    'category_key' => 'women-clothing',
    'brand_name' => 'Zara',
  ),
  11 => 
  array (
    'name' => 'جاكيت شتوي رجالي',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'جاكيت دافئ مقاوم للماء — مثالي لفصل الشتاء والرحلات الخارجية.',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-12.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 420.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 21,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'M',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 15,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'M',
        'color' => 'رمادي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#6B7280',
        'stock' => 15,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => 'L',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 15,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => 'L',
        'color' => 'رمادي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#6B7280',
        'stock' => 15,
        'sku' => NULL,
        'sort_order' => 3,
      ),
      4 => 
      array (
        'size' => 'XL',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 15,
        'sku' => NULL,
        'sort_order' => 4,
      ),
      5 => 
      array (
        'size' => 'XL',
        'color' => 'رمادي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#6B7280',
        'stock' => 15,
        'sku' => NULL,
        'sort_order' => 5,
      ),
    ),
    'category_key' => 'men-clothing',
    'brand_name' => 'The North Face',
  ),
  12 => 
  array (
    'name' => 'حقيبة ظهر عصرية',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'حقيبة ظهر متعددة الجيوب — مناسبة للجامعة والعمل والسفر.',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-13.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 190.0,
    'wholesale_price' => NULL,
    'compare_price' => 230.0,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 22,
    'variants' => 
    array (
      0 => 
      array (
        'size' => NULL,
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#1a1a1a',
        'stock' => 15,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => NULL,
        'color' => 'بني',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#78350F',
        'stock' => 15,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => NULL,
        'color' => 'رمادي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#6B7280',
        'stock' => 15,
        'sku' => NULL,
        'sort_order' => 2,
      ),
    ),
    'category_key' => 'women-bags',
    'brand_name' => 'Balenciaga',
  ),
  13 => 
  array (
    'name' => 'حذاء رياضي أطفال',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'حذاء خفيف ومريح للأطفال — يتحمل اللعب اليومي.',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => 'products/prod-14.png',
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 130.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 23,
    'variants' => 
    array (
      0 => 
      array (
        'size' => '28',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 10,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => '28',
        'color' => 'أزرق',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#2563EB',
        'stock' => 10,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => '30',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 10,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => '30',
        'color' => 'أزرق',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#2563EB',
        'stock' => 10,
        'sku' => NULL,
        'sort_order' => 3,
      ),
      4 => 
      array (
        'size' => '32',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 10,
        'sku' => NULL,
        'sort_order' => 4,
      ),
      5 => 
      array (
        'size' => '32',
        'color' => 'أزرق',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#2563EB',
        'stock' => 10,
        'sku' => NULL,
        'sort_order' => 5,
      ),
      6 => 
      array (
        'size' => '34',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#FFFFFF',
        'stock' => 10,
        'sku' => NULL,
        'sort_order' => 6,
      ),
      7 => 
      array (
        'size' => '34',
        'color' => 'أزرق',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => '#2563EB',
        'stock' => 10,
        'sku' => NULL,
        'sort_order' => 7,
      ),
    ),
    'category_key' => 'kids',
    'brand_name' => 'Nike',
  ),
  14 => 
  array (
    'name' => 'طقم رياضي أديداس نسائي',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'طقم جاكيت وبنطلون رياضي، قماش قطن مرن',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => NULL,
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'خصم',
    'price' => 180.0,
    'wholesale_price' => NULL,
    'compare_price' => 250.0,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 3,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'S',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'M',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => 'L',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => 'S',
        'color' => 'كحلي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
      4 => 
      array (
        'size' => 'M',
        'color' => 'كحلي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 4,
      ),
      5 => 
      array (
        'size' => 'L',
        'color' => 'كحلي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 5,
      ),
    ),
    'category_key' => 'women-clothing',
    'brand_name' => 'Adidas',
  ),
  15 => 
  array (
    'name' => 'فستان كاجوال صيفي',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'قماش خفيف مناسب للصيف، قصة واسعة',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => NULL,
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'جديد',
    'price' => 120.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 10,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'S',
        'color' => 'بيج',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'M',
        'color' => 'بيج',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => 'L',
        'color' => 'بيج',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => 'M',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
    ),
    'category_key' => 'women-clothing',
    'brand_name' => 'Zara',
  ),
  16 => 
  array (
    'name' => 'شنطة يد جلد',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'شنطة يد جلد صناعي فاخر، تتحمل الاستخدام اليومي',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => NULL,
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 150.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 4,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'مقاس واحد',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'مقاس واحد',
        'color' => 'بني',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
    ),
    'category_key' => 'women-bags',
    'brand_name' => 'Zara',
  ),
  17 => 
  array (
    'name' => 'حذاء رياضي أبيض نسائي',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'حذاء رياضي خفيف مريح للاستخدام اليومي',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => NULL,
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'جديد',
    'price' => 220.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 5,
    'variants' => 
    array (
      0 => 
      array (
        'size' => '36',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => '37',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => '38',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => '39',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
      4 => 
      array (
        'size' => '40',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 4,
      ),
    ),
    'category_key' => 'women-shoes',
    'brand_name' => 'Nike',
  ),
  18 => 
  array (
    'name' => 'كوتشي كاجوال',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'كوتشي كاجوال بتصميم عصري',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => NULL,
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'خصم',
    'price' => 180.0,
    'wholesale_price' => NULL,
    'compare_price' => 230.0,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 11,
    'variants' => 
    array (
      0 => 
      array (
        'size' => '37',
        'color' => 'وردي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => '38',
        'color' => 'وردي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => '39',
        'color' => 'وردي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
    ),
    'category_key' => 'women-shoes',
    'brand_name' => NULL,
  ),
  19 => 
  array (
    'name' => 'طقم رياضي US Polo',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'طقم رياضي رجالي، قماش تراكسوت أصلي',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => NULL,
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 200.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 6,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'M',
        'color' => 'أخضر',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'L',
        'color' => 'أخضر',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => 'XL',
        'color' => 'أخضر',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => 'L',
        'color' => 'كحلي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
      4 => 
      array (
        'size' => 'XL',
        'color' => 'كحلي',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 4,
      ),
    ),
    'category_key' => 'men-clothing',
    'brand_name' => 'U.S Polo',
  ),
  20 => 
  array (
    'name' => 'قميص كلاسيك',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'قميص قطني كلاسيك مناسب للعمل والمناسبات',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => NULL,
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 90.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 12,
    'variants' => 
    array (
      0 => 
      array (
        'size' => 'M',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => 'L',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => 'XL',
        'color' => 'أبيض',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
    ),
    'category_key' => 'men-clothing',
    'brand_name' => 'Zara',
  ),
  21 => 
  array (
    'name' => 'حذاء أديداس رياضي رجالي',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'حذاء رياضي بتصميم عصري ونعل مريح',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => NULL,
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'الأكثر مبيعاً',
    'price' => 250.0,
    'wholesale_price' => NULL,
    'compare_price' => 320.0,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 7,
    'variants' => 
    array (
      0 => 
      array (
        'size' => '40',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => '41',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => '42',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => '43',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
      4 => 
      array (
        'size' => '44',
        'color' => 'أسود',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 4,
      ),
    ),
    'category_key' => 'men-shoes',
    'brand_name' => 'Adidas',
  ),
  22 => 
  array (
    'name' => 'بوت تمبرلاند',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'بوت جلد طبيعي مقاوم للماء',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => NULL,
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => 'جديد',
    'price' => 380.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 13,
    'variants' => 
    array (
      0 => 
      array (
        'size' => '40',
        'color' => 'بني',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => '41',
        'color' => 'بني',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => '42',
        'color' => 'بني',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
      3 => 
      array (
        'size' => '43',
        'color' => 'بني',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 3,
      ),
    ),
    'category_key' => 'men-shoes',
    'brand_name' => 'Timberland',
  ),
  23 => 
  array (
    'name' => 'طقم أطفال رياضي',
    'name_he' => NULL,
    'name_en' => NULL,
    'description' => 'طقم رياضي مريح للأطفال، قماش قطن',
    'description_he' => NULL,
    'description_en' => NULL,
    'image' => NULL,
    'images' => NULL,
    'video' => NULL,
    'video_url' => NULL,
    'badge' => NULL,
    'price' => 90.0,
    'wholesale_price' => NULL,
    'compare_price' => NULL,
    'track_stock' => true,
    'stock_quantity' => NULL,
    'is_active' => true,
    'sort_order' => 8,
    'variants' => 
    array (
      0 => 
      array (
        'size' => '4-6 سنوات',
        'color' => 'أزرق',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 0,
      ),
      1 => 
      array (
        'size' => '7-9 سنوات',
        'color' => 'أزرق',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 1,
      ),
      2 => 
      array (
        'size' => '10-12 سنوات',
        'color' => 'أزرق',
        'color_he' => NULL,
        'color_en' => NULL,
        'color_hex' => NULL,
        'stock' => 20,
        'sku' => NULL,
        'sort_order' => 2,
      ),
    ),
    'category_key' => 'kids',
    'brand_name' => 'Adidas',
  ),
);
        foreach ($products as $prod) {
            $variants = $prod['variants'];
            unset($prod['variants']);
            $catKey = $prod['category_key'];
            unset($prod['category_key']);
            $prod['category_id'] = $categoryIds[$catKey] ?? null;
            $brandName = $prod['brand_name'];
            unset($prod['brand_name']);
            $prod['brand_id'] = $brandName ? ($brandIds[$brandName] ?? null) : null;
            $product = Product::updateOrCreate(['name' => $prod['name']], $prod);
            $product->variants()->delete();
            foreach ($variants as $variant) {
                $product->variants()->create($variant);
            }
        }

        $heroSlides = array (
  0 => 
  array (
    'image' => NULL,
    'title' => 'أحدث صيحات الموضة',
    'title_he' => 'הטרנדים האחרונים באופנה',
    'title_en' => NULL,
    'subtitle' => 'تشكيلة جديدة من الملابس والأحذية كل أسبوع',
    'subtitle_he' => 'קולקציה חדשה של בגדים ונעליים כל שבוע',
    'subtitle_en' => NULL,
    'cta_text' => 'تسوّقي الآن',
    'cta_text_he' => 'לקנייה עכשיו',
    'cta_text_en' => NULL,
    'cta_link' => NULL,
    'sort_order' => 0,
    'is_active' => true,
  ),
  1 => 
  array (
    'image' => NULL,
    'title' => 'خصومات تصل لـ 30%',
    'title_he' => 'הנחות עד 30%',
    'title_en' => NULL,
    'subtitle' => 'على تشكيلة مختارة من أفضل الماركات',
    'subtitle_he' => 'על קולקציה נבחרת מהמותגים הטובים ביותר',
    'subtitle_en' => NULL,
    'cta_text' => 'شوفي العروض',
    'cta_text_he' => 'לצפייה במבצעים',
    'cta_text_en' => NULL,
    'cta_link' => NULL,
    'sort_order' => 1,
    'is_active' => true,
  ),
  2 => 
  array (
    'image' => NULL,
    'title' => 'توصيل سريع لباب بيتك',
    'title_he' => 'משלוח מהיר עד הבית',
    'title_en' => NULL,
    'subtitle' => 'لجميع مناطق الضفة الغربية خلال 1-3 أيام عمل',
    'subtitle_he' => 'לכל אזורי הגדה המערבית תוך 1-3 ימי עסקים',
    'subtitle_en' => NULL,
    'cta_text' => 'ابدئي التسوق',
    'cta_text_he' => 'התחילו לקנות',
    'cta_text_en' => NULL,
    'cta_link' => NULL,
    'sort_order' => 2,
    'is_active' => true,
  ),
);
        foreach ($heroSlides as $slide) {
            HeroSlide::updateOrCreate(['title' => $slide['title']], $slide);
        }
    }
}
